apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-bot
  labels:
    app: bot
spec:
  replicas: {{ .Values.bot.replicaCount }}
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: bot
          image: "{{ .Values.bot.image.repository }}:{{ .Values.bot.image.tag }}"
          imagePullPolicy: {{ .Values.bot.image.pullPolicy }}
          env:
            - name: Kafka__BootstrapServers
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: Redis__ConnectionString
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: REDIS_CONNECTION
            - name: Postgres__Host
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: POSTGRES_HOST
            - name: Postgres__Database
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: POSTGRES_DATABASE
            - name: Postgres__Username
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: POSTGRES_USERNAME
            - name: Postgres__Password
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: postgres-password
          resources:
            {{- toYaml .Values.resources.bot | nindent 12 }}
